# spring
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/video?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
        username: root
        password: ''
# liquibase
    liquibase:
        enabled: true
        change-log: classpath:/liquibase/db-changelog-master.xml
        drop-first: false
    jpa:
        properties:
            hibernate:
                #        show_sql: true
                #        format_sql: true
                enable_lazy_load_no_trans: true
#    show-sql: true
#servlet:
#multipart:
#max-file-size: 200MB
#max-request-size: 200MB
jackson:
date-format: yyyy/MM/dd HH:mm
#mvc:
#favicon:
#enabled: true

server:
    servlet:
        session:
            timeout: 1d
    port: 3000